### ISSUE TITLE
C++11 features is not supported for Windows QtCreator

### ISSUE THREAD

**Issue by stepanp** [trollixx/qtcreator-tabbededitor-plugin#10]
Default Qt bundle for Windows contains QtCteator compiled with MSVC2010 compiler, so plugins need be compiled with same compiler. And MSVC2010 obviously not support C++11 :)

I think we need remove C++11 features from code. (E.g. tabbar.h\cpp containts lambdas, for-each cycles, etc.)

**Comment by trollixx** [comment]
My preference would be to ignore MSVC completely. :)

I am not sure I want to sacrifice C++11 support. It's 2015 nevertheless...

*P.S. Windows is not my primary platform, in fact, I didn't touch it for years, until I have started working on [Zeal](/zealdocs/zeal).*

**Comment by gushromp** [comment]
C++11 became the official standard almost four years ago. 

I think it would be a huge step backwards to not use it because of MSVC's sketchy/uncomplete implementation. I also don't understand why Digia hasn't switched to MSVC 12 yet for their pre-built packages.

**Comment by stepanp** [comment]
> It's 2015 nevertheless...
Say it to Digia :) 
They still build QtCreator for Windows using MSVC2010.

I have nothing against C++11, I just want to plugin can be compiled for Windows QtCreator. 
Now Windows users to use our plugin are forced to build QtCreator from sources manuallty using MinGW or make edits to the code of plugin for build it on MSVC2010 just.

**Comment by stepanp** [comment]
I did some research and found that we need make only few small changes to sucsessful build. (Lambas oddly enough are supported :)

https://github.com/trollixx/qtcreator-tabbededitor-plugin/pull/11

**Comment by trollixx** [comment]
Fixed for now, but I might break it at some point accidentally. :)
