### ISSUE TITLE
Empty project explorer widget after switching from design mode in QtCreator 3.3

### ISSUE THREAD

**Issue by stepanp** [trollixx/qtcreator-tabbededitor-plugin#6]
Steps to reproduce:
1. Open any *.ui file in desing mode
2. Click to "Edit" button in sidebar
Project explorer widget will be empty, and "Design" button in sidebar stay active.

![screen](https://cloud.githubusercontent.com/assets/615494/5992672/964fa1c2-aa43-11e4-8544-6d8c58fbcf49.png)

**Comment by gushromp** [comment]
Can confirm.

Working on a fix (if @trollixx is okay with it, unless he wishes to do it himself).

**Comment by gushromp** [comment]
Created pull request #7 that fixes this issue.
